### DISCUSSION TITLE
How to show thumbnail color instead of numaric value?

### DISCUSSION THREAD

**Discussion by jumperrg** [mdbassit/Coloris#159] [Q&A]
How to show thumbnail color instead of numeric value? Thanks!

**Comment by mdbassit** [comment]
I'm not sure I understand what you are asking. Can you please explain what you are trying to do?

**Comment by chrismec** [comment]
I think op is asking how to configure the "Full Size Thumbnail" option as shown in the demo, which is why I am here.

**Comment by chrismec** [comment]
From Demo Site:
`.full button {
      width: 100%;
      height: 100%;
 }`
```
<div class="example full">
  <input type="text" class="coloris instance3" value="#ffcc00">
</div>
```

**Reply by mdbassit** [reply]
Your CSS code will do the job, but here is a more targeted version:

```css
/* the element with the class .clr-field is automatically added by Coloris */
.clr-field button {
    width: 100%;
    height: 100%;
}
```

Or if you want to apply it to a specific set of color fields only, use a class like in your example above:

```css
.full .clr-field button {
    width: 100%;
    height: 100%;
}
```
