### ISSUE TITLE
Add 'Cancel' button (or any custom button) 

### ISSUE THREAD

**Issue by ichavchavadze** [mdbassit/Coloris#123]
Is it possible to add an extra button? I need a 'cancel' button that will do `Coloris.close(true);`

**Comment by tomickigrzegorz** [comment]
Read the documentation [closing-the-color-picker](https://github.com/mdbassit/Coloris#closing-the-color-picker)

**Comment by mdbassit** [comment]
You just need to set the `closeButton` option to **true** to display the close button. And if you want it to say "Cancel" instead of "Close" then change it with the `closeLabel` option.

**Comment by ichavchavadze** [comment]
> You just need to set the `closeButton` option to **true** to display the close button. And if you want it to say "Cancel" instead of "Close" then change it with the `closeLabel` option.

But I want all three buttons at the same time - reset, cancel, close, is it possible?

**Comment by mdbassit** [comment]
It is not possible to have all three buttons out of the box, but you can add it yourself with a little Javascript and CSS. Try this:

```js
Coloris.ready(() => {
  const picker = document.getElementById('clr-picker');
  const button = document.createElement('button');

  picker.appendChild(button);
  button.setAttribute('type', 'button');
  button.classList.add('clr-custom-reset');
  button.textContent = 'Reset';
  button.addEventListener('click', () => {
    Coloris.close(true);
  });
});
```

And to style the new button:

```css
.clr-custom-reset {
  order: 2;
  height: 24px;
  margin: 0 20px 20px 0;
  padding: 0 20px;
  border: 0;
  border-radius: 12px;
  color: #fff;
  background-color: #666;
  font-family: inherit;
  font-size: 12px;
  font-weight: 400;
  cursor: pointer;
}
```
