### ISSUE TITLE
Disable opacity? 

### ISSUE THREAD

**Issue by gitlater** [mdbassit/Coloris#2]
Is there any arguments that can disable the opacity selector?

**Comment by mdbassit** [comment]
There is no option to disable the opacity selector, but you can hide it with CSS:

```css
.clr-picker .clr-alpha {
  display: none;
}
```
