### ISSUE TITLE
How to make Coloris compatible with Skeleton CSS

### ISSUE THREAD

**Issue by Mark-81** [mdbassit/Coloris#64]
Firefox 105.x, if I render a simple page like this:

```
<!DOCTYPE html>
<html lang="en" xmlns:YYYY-MM-DDTHH="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="css/coloris.min.css">
</head>

<body>
    <div class="container">
        <input type="text" name="color1" class="coloris" value="#ff0000">
    </div>

    <script type="text/javascript" src="js/coloris.min.js"></script>
    <script>
        Coloris({
            el: '.coloris',
            theme: 'pill',
            themeMode: 'light',
            format: 'auto',
            formatToggle: true,
            alpha: 'false',
            swatches: [
                '#ff0000',
                '#ffa500',
                '#ffff00',
                '#008000',
                '#0000ff',
                '#4b0082',
                '#ee82ee',
                '#ffffff'
            ]
        });

    </script>
</body>

</html>
```

Coloris is rendered as expected:

![immagine](https://user-images.githubusercontent.com/18552813/195809145-701703de-4f98-4bc8-8291-026befcdf9d3.png)

But if I include the Skeleton CSS:

`<link rel="stylesheet" type="text/css" href="css/skeleton.min.css">` 

it becomes a mess:

![immagine](https://user-images.githubusercontent.com/18552813/195811652-e981c94b-f33d-4994-9511-f4b6b9510c4b.png)

![immagine](https://user-images.githubusercontent.com/18552813/195811691-e7b3eb8d-8956-43e2-9bfb-fea961ed95a6.png)

Is there a way to force the compatibility with Skeleton CSS (or any other CSS) ?

By the way, the `alpha` setting is not honored.

**Comment by mdbassit** [comment]
Unfortunately it's impossible to predict how each CSS library/framework will pollute the default styles. It's possible to fix the issues in your own CSS code though. Just add this to your stylesheet:

```css
.clr-preview {
  padding: 0;
}

.clr-segmented label {
  margin: 0;
  font-weight: normal;
  line-height: initial;
}

.clr-swatches button {
  padding: 0;
}

.clr-field input {
  margin: 0;
}

.clr-field button {
  margin: 0;
  padding: 0;
}
```

The alpha setting works, but you set it incorrectly. It should be `alpha: false` not `alpha: 'false'`.
