### ISSUE TITLE
Buttons: Clear and Close depending on IL8N

### ISSUE THREAD

**Issue by melloware** [mdbassit/Coloris#80]
Testing a bunch of our translations here is French for example depending on the options selected it renders off.  Not sure what we can do about it?

Polaroid:
![image](https://user-images.githubusercontent.com/4399574/218113307-ec8c47a5-a174-4865-adbb-975f1f1902ac.png)

Pill:
![image](https://user-images.githubusercontent.com/4399574/218113403-464f0eba-1380-4991-81c2-07599fbcd81a.png)

Here is Swedish for example:
![image](https://user-images.githubusercontent.com/4399574/218113896-0b47335d-0b58-4663-96cb-3dc46f98a447.png)

**Comment by mdbassit** [comment]
Some CSS customisation should fix it. For instance you could try increasing the width of the dialog like this:

```css
/* Increase the width of the dialog by 20px for the default and polaroid themes */
.clr-picker {
  width: 220px;
}

/* Increase the width of the dialog by 20px for the pill theme */
.clr-picker.clr-pill {
  width: 400px;
}
```

This should be added to your page after including coloris.min.css.
