### ISSUE TITLE
mousemove event not removed when i release mouse on iFrame

### ISSUE THREAD

**Issue by giacomarco** [mdbassit/Coloris#99]
Good morning,
Status:
coloris initialize on document in a column. and close to this column I have an Iframe.
when I open coloris box half of gradient picker are over the iframe.

When I release 'mouseup' the mouse on iframe ( if i choose  color on the edge it's 99% times) the event 'mousemove' is not removed because the document. it's different. 
It's not so easy to explain and I'm sorry for my eng.
I hope that you understand. 
Thank you Marco

**Comment by giacomarco** [comment]
yesterday I create a workaround for fixit 
i'll share my solution I add this at line 959 in coloris.js: 
```javascript
 const cover = document.createElement('div')
    cover.classList.add('clr-cover');
    cover.addEventListener('click', ()=> {
      closePicker();
    })
    picker.appendChild(cover);
``` 

and this  in coloris.css
```css
#clr-picker .clr-cover {
  content: '';
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: transparent;
  z-index: -1;
}
``` 

this create a transparent layer under the picker that cover all window.

**Comment by mdbassit** [comment]
If that kind of fix is good enough for you, then you don't even need to modify `coloris.js`. Just add this CSS code to your page:

```css
.clr-picker:after {
  content: '';
  position: fixed;
  width: 100vw;
  height: 100vh;
  top: 0;
  left: 0;
  z-index: -1;
  background: transparent;
}
```

But with you won't be able to click outside to close the color picker.

**Comment by mdbassit** [comment]
In that case here is a version that doesn't force you to modify the color picker itself.

Add this CSS code anywhere in your page:

```css
.clr-picker.clr-open .clr-backdrop {
  position: fixed;
  width: 100vw;
  height: 100vh;
  top: 0;
  left: 0;
  z-index: -1;
  background: transparent;
}
```

And add this Javascript code after initializing the color picker:

```js
function clrFixIframeMouseUp() {
  const picker = document.getElementById('clr-picker');
  const backdrop = document.createElement('div');

  picker.appendChild(backdrop);
  backdrop.classList.add('clr-backdrop');
  backdrop.addEventListener('click', () => {
    Coloris.close();
  });
}

// Wait foe the docuemnt to load first
if (document.readyState !== 'loading') {
  clrFixIframeMouseUp();
} else {
  document.addEventListener('DOMContentLoaded', function () {
    clrFixIframeMouseUp();
  });
}
```
